version: "3"

services:
  app:
    container_name: ether_bank
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - 5000:5000
    env_file:
      - .env
    volumes:
      - ".:/home/node/app"
      - "./docker/run.sh:/usr/bin/run.sh"
    networks:
      - ether_net

  mongo:
    image: mongo:4.2
    container_name: ether_mongo
    ports:
      - 27017
    volumes:
      - "./docker/.data/mongo:/var/lib/mongo"
    networks:
      - ether_net

  redis:
    image: redis:6.0.5-alpine
    container_name: ether_redis
    ports:
      - 6376
    volumes:
      - "./docker/.data/redis:/data"
    networks:
      - ether_net

networks:
  ether_net:
