version: '3'

services:
  app:
    container_name: ether_bank
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - 5000:5000
    env_file:
      - .env
    volumes:
      - ".:/home/node/app"
      - "./docker/run.sh:/usr/bin/run.sh"
